### ISSUE TITLE
runing problem

### ISSUE THREAD

**Issue by hideon27** [ljaiverson/pgfed#1]
when i run the code ‘python main.py -data cifar10 -nc 25 -jr 0.25 -gr 2 -ls 2 -algo PGFed -mu 0.1 -lam 0.01 -bt 0.0’，i got the result that
File path: ../results/cifar10-25clients_alpha0.3-PGFed-lr:0.00500-mu:0.10000-lambda:0.01000-cnn-0.h5
Traceback (most recent call last):
  File "C:\Users\...\Desktop\pgfed-main\system\main.py", line 214, in <module>
    run(args)
  File "C:\Users\...\Desktop\pgfed-main\system\main.py", line 106, in run
    server.train()
  File "C:\Users\...\Desktop\pgfed-main\system\flcore\servers\serverpgfed.py", line 64, in train
    self.save_results(fn=self.hist_result_fn)
  File "C:\Users\...\Desktop\pgfed-main\system\flcore\servers\serverbase.py", line 221, in save_results
    with h5py.File(file_path, 'w') as hf:
  File "D:\a_environment\anaconda\envs\env1\lib\site-packages\h5py\_hl\files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "D:\a_environment\anaconda\envs\env1\lib\site-packages\h5py\_hl\files.py", line 237, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 126, in h5py.h5f.create
OSError: [Errno 22] Unable to create file (unable to open file: name = '../results/cifar10-25clients_alpha0.3-PGFed-lr:0.00500-mu:0.10000-lambda:0.01000-cnn-0.h5', errno = 22, error message = 'Invalid argument', flags = 13, o_flags = 302)

i think there is something wrong with the function that meant to save the result of the training(probably the way to create the file to restore the result), can u give me some advice on how to solve the problem i mentioned, thank u for ur devotion.

**Comment by ljaiverson** [comment]
Hi @hideon27
Thank you for your question. What OS are you running the code on? I am not able to reproduce the error, but I think the error happens since the `file_path` is incompatible with your OS. I would suggest changing the `file_path` variable to something simple, like "results.h5", and see if the error happens again.
